#!/usr/bin/python3

import os
from typing import Union

from rofication import RoficationGui, RoficationClient, resources, Resource

if __name__ == '__main__':
    # defaults
    label_icon: Resource = resources.notify_none
    label_color: Resource = resources.label_color
    value_color: Resource = resources.value_color
    value_font: Resource = resources.value_font

    before_color = Resource(env_name='i3xrocks_rofication_before_color', xres_name='i3xrocks.rofication.before.color', default='#7B8394')
    before_icon = Resource(env_name='i3xrocks_before_icon', xres_name='i3xrocks.before.icon', default='')
    after_color = Resource(env_name='i3xrocks_rofication_after_color', xres_name='i3xrocks.rofication.after.color', default='#7B8394')
    after_icon = Resource(env_name='i3xrocks_after_icon', xres_name='i3xrocks.after.icon', default='')

    num: Union[int, str]
    try:
        client = RoficationClient()

        if os.getenv('button'):
            RoficationGui(client).run()

        num, crit = client.count()
        if num > 0:
            label_icon = resources.notify_some
            value_color = resources.warning_color
        if crit > 0:
            value_color = resources.critical_color
    except (FileNotFoundError, ConnectionRefusedError):
        label_icon = resources.notify_error
        label_color = resources.critical_color
        num = '?'

    # only fetch resources if needed
    before = f'<span foreground="{before_color.fetch()}">{before_icon.fetch()}</span>'
    after = f'<span foreground="{after_color.fetch()}">{after_icon.fetch()}</span>'
    label = f'<span foreground="{label_color.fetch()}">{label_icon.fetch()}</span>'
    value = f'<span font_desc="{value_font.fetch()}" foreground="{value_color.fetch()}"> {num}</span>'
    print(before + label + value + after)
